-- 관리자 화면

CREATE TABLESPACE schoolsDB
DATAFILE 'C:/oraclexe/data/schoolsdb.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

DROP TABLESPACE schoolsDB
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS; 

CREATE USER schools IDENTIFIED BY schools
DEFAULT TABLESPACE schoolsDB;

GRANT DBA TO schools;

